const OPERATIONAL_LOG_TYPE = 'OPERATIONAL_LOG_TYPE';
const BUSINESS_LOG_TYPE = 'BUSINESS_LOG_TYPE';
const INFO_SEVERITY = 'INFO';
const ERROR_SEVERITY = 'ERROR';
const BUY_ACTION = 'BUY';
const SELL_ACTION = 'SELL';
const RSI_OVER_BOUGHT_LIMIT = 66;
const RSI_OVER_SOLD_LIMIT = 34;
const CROSS_DEATH_200 = 'CROSS_DEATH_200';
const CROSS_GOLDEN_200 = 'CROSS_GOLDEN_200';
const BELOW_OPERATOR = 'BELOW_OPERATOR';
const ABOVE_OPERATOR = 'ABOVE_OPERATOR';
const CURRENT_QUOTE = 'CURRENT_QUOTE';
const ABSOLUTE_VARIANCE = 'ABSOLUTE_VARIANCE';
const PERCENTAGE_VARIANCE = 'PERCENTAGE_VARIANCE';
const EQUAL_ASSERT_TYPE = 'EQUAL_ASSERT_TYPE';

module.exports = {
  OPERATIONAL_LOG_TYPE,
  BUSINESS_LOG_TYPE,
  INFO_SEVERITY,
  ERROR_SEVERITY,
  BUY_ACTION,
  SELL_ACTION,
  RSI_OVER_BOUGHT_LIMIT,
  RSI_OVER_SOLD_LIMIT,
  CROSS_DEATH_200,
  CROSS_GOLDEN_200,
  BELOW_OPERATOR,
  ABOVE_OPERATOR,
  CURRENT_QUOTE,
  ABSOLUTE_VARIANCE,
  PERCENTAGE_VARIANCE,
  EQUAL_ASSERT_TYPE,
};
